#!/usr/bin/env python3

def init_my_db(cursor):
        def not_exists(sql, table):
                sql.execute(f"""SELECT * FROM {table};""")
                vlue = sql.fetchall()
                if (len(vlue) == 0):
                        return True
                else:
                        return False

        guild_creator = """CREATE TABLE IF NOT EXISTS
        guilds(id_guild INTEGER PRIMARY KEY AUTOINCREMENT, guild_name TEXT, level INTEGER, money INTEGER, best_scr INTEGER, best_niv INTEGER)"""

        player_creator = """CREATE TABLE IF NOT EXISTS
        players(id_guild INTEGER PRIMARY KEY, path TEXT, perso TEXT, type TEXT, vit INTEGER, life INTEGER, res INTEGER, mana INTEGER, xp INTEGER, desc TEXT, inc_speed FLOAT, max_size FLOAT, FOREIGN KEY (id_guild) REFERENCES guilds(id_guild))"""

        character_creator = """CREATE TABLE IF NOT EXISTS
        players(path TEXT, perso TEXT, type TEXT, vit INTEGER, life INTEGER, res INTEGER, mana INTEGER, xp INTEGER, desc TEXT)"""

        monster_creator = """CREATE TABLE IF NOT EXISTS
        monsters(grade INTEGER, path TEXT, perso TEXT, vit INTEGER, life INTEGER, res INTEGER, mana INTEGER, desc TEXT, inc_speed FLOAT, max_size FLOAT)"""

        skill_m_creator = """CREATE TABLE IF NOT EXISTS skill_m(skills TEXT, perso TEXT, vit_a INTEGER, life_a INTEGER, res_a INTEGER, mana_a INTEGER,
        vit INTEGER, life INTEGER, res INTEGER, mana INTEGER, frame INTEGER, efct_a TEXT, efct TEXT, desc TEXT)"""

        skill_creator = """CREATE TABLE IF NOT EXISTS skill(xp INTEGER, skills TEXT, perso TEXT, vit_a INTEGER, life_a INTEGER, res_a INTEGER, mana_a INTEGER,
        vit INTEGER, life INTEGER, res INTEGER, mana INTEGER, frame INTEGER, efct_a TEXT, efct TEXT, desc TEXT)"""

        inventory_creator = """CREATE TABLE IF NOT EXISTS
        market(id_guild INTEGER PRIMARY KEY, obj TEXT, image TEXT, price INTEGER, frame INTEGER, type TEXT, vit INTEGER, life INTEGER, res INTEGER, mana INTEGER, need INTEGER, info TEXT, FOREIGN KEY (id_guild) REFERENCES guilds(id_guild))"""

        market_creator = """CREATE TABLE IF NOT EXISTS
        market(obj TEXT, image TEXT, price INTEGER, frame INTEGER, type TEXT, vit INTEGER, life INTEGER, res INTEGER, mana INTEGER, need INTEGER, info TEXT)"""

        cursor.execute(guild_creator)
        cursor.execute(player_creator)
        cursor.execute(character_creator)
        cursor.execute(monster_creator)
        cursor.execute(skill_creator)
        cursor.execute(skill_m_creator)
        cursor.execute(inventory_creator)
        cursor.execute(market_creator)

        if not_exists(cursor, "guilds"):
                cursor.execute('''
                        INSERT INTO guilds (guild_name, level, money, best_scr, best_niv)
                        VALUES ('Default', 0, 1000, 0, 0) ''')
                cursor.execute("""SELECT id_guild FROM guilds WHERE guild_name = 'Default'""")
                vlue = cursor.fetchall()[0][0]
                cursor.execute("""INSERT INTO players (id_guild, path, perso, type, vit, life, res, mana, xp, desc, inc_speed, max_size) VALUES (?, "./ressources/players/lucas.png", "Lucas", "c", 30, 60, 15, 100, 0, "Marques, a half-man, half-god demigod, walks the realms with unparalleled determination. As a devoted servant of Azaka Medeh, the benevolent god of agriculture, Marques tends to the earth with his powerful hands. His roots in both the divine and earthly realms make him a force to be reckoned with. In the face of a mysterious virus threatening both worlds, Marques embarks on a daring journey, uncovering secrets and facing astonishing beings to break the curse that plagues the kingdom", 0.15, 2)""", (vlue,))

        if not_exists(cursor, "skill_m"):
                cursor.execute("""INSERT INTO skill_m VALUES ("Read devil", "Book", 0, 0, 0, -5, 0, -10, 0, 0, 1, "ressources/effect/thunder", "ressources/effect/slash", " The book triggers an attack resembling a Devil.")""")
                cursor.execute("""INSERT INTO skill_m VALUES ("Book misery", "Book", 0, 0, 0, -10, 0, 0, 0, -3, 1, "ressources/effect/thunder", "ressources/effect/slash", "The book inflicts a curse that brings misery.")""")
                cursor.execute("""INSERT INTO skill_m VALUES ("Bite hard poison", "Anaconda", 0, 0, 0, -20, 0, -15, 0, -15, 2, "ressources/effect/thunder", "ressources/effect/slash", "The anaconda attacks by biting hard.")""")
                cursor.execute("""INSERT INTO skill_m VALUES ("Shield bash", "Anaconda", 0, 0, 15, -10, 0, 0, 0, 0, 1, "ressources/effect/thunder", "ressources/effect/slash", "The anaconda uses its body as a shield to protect himself")""")
                cursor.execute("""INSERT INTO skill_m VALUES ("Death dance", "Anaconda", 0, 0, 0, 0, 0, -25, 0, 0, 1, "ressources/effect/thunder", "ressources/effect/slash", "The anaconda performs a deadly dance, dealing damage.")""")
                cursor.execute("""INSERT INTO skill_m VALUES ("Pot pot curse", "Pot", 0, 0, 15, -15, 0, 10, 0, 0, 1, "ressources/effect/thunder", "ressources/effect/slash", "The pot casts a potential curse.")""")
                cursor.execute("""INSERT INTO skill_m VALUES ("Fireball", "Devil", 0, 0, 0, 15, 0, 0, -5, -15, 1, "ressources/effect/thunder", "ressources/effect/slash", "The Devil hurls a fireball at the enemy.")""")
                cursor.execute("""INSERT INTO skill_m VALUES ("Reverse", "Devil", 0, 18, 0, -15, 0, -18, 0, 0, 1, "ressources/effect/thunder", "ressources/effect/slash", " The Devil summons a dark aura to strengthen its defenses.")""")

        if not_exists(cursor, "skill"):
                cursor.execute("""INSERT INTO skill VALUES (0, "Slash", "Lucas", 0, -20, -5, 0, 0, 0, 0, 0, 1, "ressources/effect/thunder", "ressources/effect/slash", "Performs a sharp attack with a sword")""")
                cursor.execute("""INSERT INTO skill VALUES (0, "Divine slash", "Lucas", 0, -30, -10, 0, 0, 0, 0, -20, 1, "ressources/effect/thunder", "ressources/effect/slash", "Unleashes a sharp attack with mana")""")
                cursor.execute("""INSERT INTO skill VALUES (0, "Shield bash", "Lucas", 0, 0, 0, 0, 0, 0, 15, 0, 1, "ressources/effect/thunder", "ressources/effect/slash", "having defensive effects.")""")

        if not_exists(cursor, "monsters"):
                cursor.execute("""INSERT INTO monsters VALUES (1, "./ressources/monsters/Evilbook", "Book", 20, 20, 5, 30, "A malevolent book that possesses dark knowledge. Its pages hold curses that can bring harm to those who encounter it.", 0, 0)""")
                cursor.execute("""INSERT INTO monsters VALUES (1, "./ressources/monsters/Demonpot", "Pot", 5, 25, 10, 30, "A sinister pot with demonic energies. It can brew curses and unleash them upon unsuspecting adventurers", 0.15, 19)""")
                cursor.execute("""INSERT INTO monsters VALUES (2, "./ressources/monsters/anaconda", "Anaconda",  25, 80, 20, 30, "A formidable anaconda with a powerful bite. Its swift movements make it a challenging opponent in the jungle.", 0, 0)""")
                cursor.execute("""INSERT INTO monsters VALUES (2, "./ressources/monsters/devil", "Devil", 20, 60, 10, 70, "A malevolent devil with mastery over fire. Its demonic aura engulfs the surroundings, and it can unleash destructive fireballs upon its foes.", 0, 0)""")

        if not_exists(cursor, "market"):
                cursor.execute("""INSERT INTO market VALUES ('Elixir of vitality', './ressources/market/object/pv.png', 225, 1, 'cgsa', 0, 2, 0, 0, 0, "Elixir of Vitality\nThe Elixir of Vitality is a rare and precious concoction that embodies the very essence of life itself. Encased in a delicate crystal vial with a golden stopper, it radiates a soft, ethereal glow that seems to pulse in rhythm with the heartbeat of the universe.\nCrafted by ancient alchemists and blessed by benevolent deities, this elixir is believed to be a gift from the gods to mortals. It is said that even a single drop of the Elixir of Vitality can rejuvenate the weary, heal the wounded, and extend the boundaries of one's life.\nWhen consumed, the elixir imparts a profound sense of well-being and boundless energy. Wounds mend swiftly, fatigue dissipates, and the spirit soars with renewed vigor. It is a source of hope and resilience, a beacon of life in the darkest of times.\nHowever, the Elixir of Vitality is exceedingly rare, and its creation is a closely guarded secret. Those fortunate enough to possess it are entrusted with a great responsibility—to use its power wisely and protect the fragile balance between life and death. It is a reminder that in the face of adversity, the elixir offers not just physical strength but also the resilience of the human spirit, a testament to the enduring power of life itself.", 0)
                ('Elixir of vitality', './ressources/market/object/pv.png', 225, 1, 'cgsa', 0, 20, 0, 0, 0, "Elixir of Vitality\nThe Elixir of Vitality is a rare and precious concoction that embodies the very essence of life itself. Encased in a delicate crystal vial with a golden stopper, it radiates a soft, ethereal glow that seems to pulse in rhythm with the heartbeat of the universe.\nCrafted by ancient alchemists and blessed by benevolent deities, this elixir is believed to be a gift from the gods to mortals. It is said that even a single drop of the Elixir of Vitality can rejuvenate the weary, heal the wounded, and extend the boundaries of one's life.\nWhen consumed, the elixir imparts a profound sense of well-being and boundless energy. Wounds mend swiftly, fatigue dissipates, and the spirit soars with renewed vigor. It is a source of hope and resilience, a beacon of life in the darkest of times.\nHowever, the Elixir of Vitality is exceedingly rare, and its creation is a closely guarded secret. Those fortunate enough to possess it are entrusted with a great responsibility—to use its power wisely and protect the fragile balance between life and death. It is a reminder that in the face of adversity, the elixir offers not just physical strength but also the resilience of the human spirit, a testament to the enduring power of life itself.", 0) ('Ring of resilience', './ressources/market/object/bague.png', 450, 1, 'cgsa', 0, 0, 3, 0, 1, "**Ring of Resilience**\nThe Ring of Resilience is a finely crafted band of polished obsidian, adorned with intricate silver runes that pulse with a faint, protective energy. When worn, it bestows upon the bearer an extraordinary resistance to adversity.\nThis mystical ring forms an unbreakable shield around the wearer, enhancing their physical and mental fortitude. It reduces the impact of physical blows, wards off debilitating ailments, and bolsters the wearer's willpower in moments of challenge.\nA symbol of unyielding determination, the Ring of Resilience serves as a guardian against the harshest of trials. It is a steadfast companion for those who dare to confront the darkest of forces and a beacon of hope in the face of overwhelming odds.", 0)
                ('The Astral Triad Ring', './ressources/market/object/bague2.png', 3000, 3, 'cgsa', 20, 0, 4, 5, 2, "**The Astral Triad Ring**\nThe Astral Triad Ring is an exceedingly rare and legendary artifact, a masterful fusion of mystical craftsmanship and divine energy. This enigmatic ring embodies the trinity of speed, power, and resilience.\nCrafted from the elusive Starstone, a gem found only in the heart of meteorites, the Astral Triad Ring shimmers with a cosmic brilliance. It boasts a design adorned with celestial motifs that seem to dance and shimmer with the light of distant stars.\nWhen donned, this remarkable ring grants its wearer unparalleled abilities. They move with the swiftness of a shooting star, their strength rivals that of titans, and their resilience is akin to the enduring mountains. It is the embodiment of the heavens' favor, a symbol of the chosen few who have been blessed by the cosmos.\nThe Astral Triad Ring is a testament to the rarity of such power, an artifact of immense value, and a beacon for those destined to rewrite the very fabric of fate.", 3)
                ('Blade of twilight', './ressources/market/object/sword25.png', 300, -1, 'c', 0, 0, 0, 0, 1, "**Blade of Twilight**\nThe Blade of Twilight is a two-star grade sword, a balanced and reliable weapon with an unassuming appearance. Its hilt is wrapped in well-worn leather, and the blade, though simple in design, holds a unique quality that sets it apart.\nForged by skilled artisans, the Blade of Twilight possesses a subtle enchantment that enhances the wielder's strength and agility. It is a dependable companion for those who seek a versatile weapon for both offense and defense.\nWhen drawn under the moon's gentle light, the blade seems to shimmer with a faint, silvery glow, invoking the mystique of the night. It is a trusted ally for adventurers, providing them with just enough power to overcome challenges while maintaining a level of finesse and control.\nThe Blade of Twilight may not be as formidable as legendary weapons, but its reliability and adaptability make it a sought-after choice for those who value a balanced and versatile blade on their journeys.", 2)
                ('Sword of Empyreal Migth', './ressources/market/object/sword67.png', 4200, -1, 'c', 0, 0, 0, 3, 1, '**Sword of Empyreal Might**\nThe Sword of Empyreal Might is a legendary blade forged in the heart of an ancient volcano and imbued with the essence of elemental fire. This awe-inspiring weapon radiates an incandescent glow, and its blade seems to ripple with flames when drawn.\nWhen wielded by a skilled warrior, the Sword of Empyreal Might channels the fiery power of the heavens, granting its bearer unparalleled strength. With each swing, it engulfs enemies in searing infernos and bestows upon its master the might of a demigod.\nThe sword is not only a symbol of power but also a conduit to the elemental forces themselves. It is said that those who harness its fiery energy can command the very flames of creation, making it an instrument of both destruction and rebirth.\nThe Sword of Empyreal Might is an artifact of immense significance and rarity, a weapon sought by heroes and conquerors alike, for it is said that the one who wields it can shape the destiny of nations with the fury of a blazing tempest.', 6)
                ('Golden Radiance Staff', './ressources/market/object/sorcerer.png', 4800, -1, 's', 0, 0, 0, 8, 2, 'Golden Radiance Staff\nThe Golden Radiance Staff is a magical relic of the gold class, gleaming with an ethereal golden glow. This artifact is renowned for its potent channeling of magical energy,\ncapable of unleashing spells and incantations of extraordinary magnitude. It stands as an iconic tool for the most seasoned wizards and enchanters, \nenabling them to manipulate mystical forces with precision and power.', 3)
                ('Sword of Fangs', './ressources/market/object/fang.png', 605, -1, 'c', 0, 0, 0, 0, 0, '**Sword of Fangs**\nThe Sword of Fangs is a finely crafted blade with serrated edges, resembling the fearsome teeth of a mythical serpent. This silver grade weapon is known for its exceptional slicing and piercing capabilities,\nmaking it a deadly choice for those who seek to strike swiftly and inflict grievous wounds on their adversaries.', 3)
                ('Bronze Tide', './ressources/market/object/trident.png', 255, -1, 's', 0, 0, 0, 3, 0, '**Bronze Tide Trident**\nThe Bronze Tide Trident is a formidable aquatic weapon of bronze-level craftsmanship. This trident, while not as extravagant as its higher-tier counterparts, is a reliable choice for those who navigate the depths.\nIts three prongs are designed for precision and striking power,\nmaking it a trusted companion for underwater adventures and battles beneath the waves.', 0)
                ('Specter of Stellar Ascension', './ressources/market/object/divine.png', 2000, 4, 'g', 4, 0, 3, 0, 2, '**Specter of Stellar Ascension**\nThe Specter of Stellar Ascension is a sacred relic gifted by the God of Combat, a celestial boon for those who yearn to transcend their limits in battle. This ethereal specter,\nwhen invoked, transforms its wielder into a flurry of stardust, granting unparalleled martial prowess. It enhances strength, agility, and battle intuition to the utmost degree, allowing warriors to reach the zenith of their combat potential.\nWith the Specter of Stellar Ascension, mortal champions become cosmic avatars of combat.', 9)
                ('Axe of valor', './ressources/market/object/axe.png', 605, -1, 'c', 0, 0, 3, 0, 0, '**Axe of Valor**\nThe Axe of Valor is a battle-worn weapon favored by warriors on the front lines. This trusty axe, with its rugged design and razor-sharp edge, instills a sense of courage and determination in those who wield it.\nIts weighty swing and relentless chopping power make it a formidable choice for those who thrive in the chaos of combat. With the Axe of Valor in hand, warriors carve their paths to glory.*', 3)""")
